language: csharp
solution: lfmachadodasilva.MyExpenses.sln

mono: none
dotnet: 2.1.502
script:
 - dotnet restore
 
jobs:
  include:
    - stage: building
      script: dotnet build /p:Configuration=Release
    - stage: unit-testing
      script: dotnet test
